CREATE TABLE TABELA_DOSTAWCY(
IDDOSTAWCY VARCHAR(5) PRIMARY KEY,
DOSTAWCA VARCHAR(30) NOT NULL,
KOD_POCZTOWY VARCHAR(6) NOT NULL,
MIASTO VARCHAR(20) NOT NULL,
ULICA VARCHAR(20) NOT NULL,
NR_BUDYNKU INT NOT NULL,
NR_MIESZKANIA INT);

CREATE TABLE TABELA_PRODUKTY(
IDPRODUKTU VARCHAR(5) PRIMARY KEY,
NAZWAPRODUKTU VARCHAR(30) NOT NULL,
CENANETTO INT NOT NULL,
CENABRUTTO INT NOT NULL);

CREATE TABLE TABELA_DOSTAWY(
IDDOSTAWY VARCHAR(5) PRIMARY KEY,
IDDOSTAWCY VARCHAR(5) NOT NULL,
IDPRODUKTU VARCHAR(5) NOT NULL);

ALTER TABLE TABELA_DOSTAWY ADD FOREIGN KEY (IDPRODUKTU) REFERENCES TABELA_PRODUKTY(IDPRODUKTU);
ALTER TABLE TABELA_DOSTAWY ADD FOREIGN KEY (IDDOSTAWCY) REFERENCES DOSTAWCY(IDDOSTAWCY);
