CREATE TABLE TABELA_PRACOWNICY(
IDPRACOWNIKA VARCHAR(5) PRIMARY KEY,
IMIE VARCHAR(10) NOT NULL,
NAZWISKO VARCHAR(30) NOT NULL);

CREATE TABLE TABELA_PACJENCI(
IDPACJENTA VARCHAR(5) PRIMARY KEY,
IMIE VARCHAR(10) NOT NULL,
NAZWISKO VARCHAR(30) NOT NULL);

CREATE TABLE TABELA_ZABIEGI(
IDZABIEGU VARCHAR(5) PRIMARY KEY,
NAZWAZABIEGU VARCHAR(20) NOT NULL);

CREATE TABLE TABELA_WIZYTY(
IDWIZYTY INT PRIMARY KEY,
DATA DATE NOT NULL,
GODZINA DATE NOT NULL,
IDPACJENTA VARCHAR(5) NOT NULL,
IDPRACOWNIKA VARCHAR(5) NOT NULL,
IDZABIEGU VARCHAR(5) NOT NULL);

ALTER TABLE WIZYTY ADD FOREIGN KEY (IDPACJENTA) REFERENCES PACJENCI (IDPACJENTA);
ALTER TABLE WIZYTY ADD FOREIGN KEY (IDPRACOWNIKA) REFERENCES PRACOWNICY (IDPRACOWNIKA);
ALTER TABLE WIZYTY ADD FOREIGN KEY (IDZABIEGU) REFERENCES ZABIEGI (IDZABIEGU);